baseURL = "/"
languageCode = "en-us"
title = "Keith Alpichi"
theme = "coder"
enableEmoji = true
disqusShortname = "keithalpichi"
enableRobotsTXT = true
googleAnalytics = "UA-49683420-3"
pygmentsStyle = "pastie"

[params] # theme parameters
    author = "Keith Alpichi" # author's name
    info = "Software Engineer, Coffee Addict, Fit Fanatic, Cook, and California Beach Bum"
    description = "Keith Alpichi's Portfolio & Blog" # site description
    keywords = "blog,software engineer,software,developer,web development,code" # site keywords

[permalinks]
  post = ":slug"

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/keithalpichi/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/keithalpichi/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/keithalpiochi/"
[[params.social]]
    name = "Stackoverflow"
    weight = 4
    url = "https://stackoverflow.com/users/5796559/keitha"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
